name = "standard"
starting_tile = "CRFR"

[tile-filenames]
CCCC_PENNANT = "CCCC_PENNANT.tile"
CCFC = "CCFC.tile"
CCFC_PENNANT = "CCFC_PENNANT.tile"
CCFF = "CCFF.tile"
CCFF_DISCONNECTED = "CCFF_DISCONNECTED.tile"
CCFF_PENNANT = "CCFF_PENNANT.tile"
CCRC = "CCRC.tile"
CCRC_PENNANT = "CCRC_PENNANT.tile"
CCRR = "CCRR.tile"
CCRR_PENNANT = "CCRR_PENNANT.tile"
CFCF = "CFCF.tile"
CFCF_DISCONNECTED = "CFCF_DISCONNECTED.tile"
CFCF_PENNANT = "CFCF_PENNANT.tile"
CFFF = "CFFF.tile"
CFRR = "CFRR.tile"
CRFR = "CRFR.tile"
CRRF = "CRRF.tile"
CRRR_DISCONNECTED = "CRRR_DISCONNECTED.tile"
FFFF_CLOISTER = "FFFF_CLOISTER.tile"
FFRF_CLOISTER = "FFRF_CLOISTER.tile"
FFRR = "FFRR.tile"
FRFR = "FRFR.tile"
FRRR_DISCONNECTED = "FRRR_DISCONNECTED.tile"
RRRR = "RRRR.tile"

[tile-numbers]
CCCC_PENNANT = 1
CCFC = 3
CCFC_PENNANT = 1
CCFF = 3
CCFF_DISCONNECTED = 2
CCFF_PENNANT = 2
CCRC = 1
CCRC_PENNANT = 2
CCRR = 3
CCRR_PENNANT = 2
CFCF = 1
CFCF_DISCONNECTED = 3
CFCF_PENNANT = 2
CFFF = 5
CFRR = 3
CRFR = 4
CRRF = 3
CRRR_DISCONNECTED = 3
FFFF_CLOISTER = 4
FFRF_CLOISTER = 2
FFRR = 9
FRFR = 8
FRRR_DISCONNECTED = 4
RRRR = 1